
CREATE TABLE USERS (
    ID INT NOT NULL AUTO_INCREMENT,
    LAST_NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    EMAIL_ID VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(1000) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID)
);
ALTER TABLE USERS ADD COLUMN VERIFIED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE USERS ADD CONSTRAINT EMAILID_UNIQUE UNIQUE (EMAIL_ID);

CREATE TABLE PRODUCT (
    ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);

CREATE TABLE ITEM (
    ID INT NOT NULL AUTO_INCREMENT,
	PRODUCT_ID INT,
	RATING INT NOT NULL,
	PRICE INT NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ITEM PRIMARY KEY (ID),
	CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

CREATE TABLE CART (
    ID INT NOT NULL AUTO_INCREMENT,
	EMAIL_id VARCHAR(255) NOT NULL,
	PRODUCT_ID INT NOT NULL,
	PRODUCT_CATEGORY VARCHAR(255) NOT NULL,
	ITEM_ID INT NOT NULL,
	ITEM_DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE INT NOT NULL,
    CONSTRAINT PK_item PRIMARY KEY (ID),
	CONSTRAINT FK_CART_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
	CONSTRAINT FK_CART_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID)
);


CREATE TABLE ORDERS (
	ID INT NOT NULL AUTO_INCREMENT,
	EMAIL_id VARCHAR(255) NOT NULL,
	PRODUCT_CATEGORY VARCHAR(255) NOT NULL,
	ITEM_DESCRIPTION VARCHAR(255) NOT NULL,
	PRICE INT NOT NULL, 
	CONSTRAINT PK_ORDER PRIMARY KEY (ID)
);
INSERT INTO PRODUCT(DESCRIPTION) VALUES ("IPHONE");
INSERT INTO PRODUCT(DESCRIPTION) VALUES ("LAPTOP");
INSERT INTO PRODUCT(DESCRIPTION) VALUES ("BAG");



INSERT INTO ITEM(PRODUCT_ID,RATING,PRICE,DESCRIPTION) VALUES (1,5,200,"IPHONE");
INSERT INTO ITEM(PRODUCT_ID,RATING,PRICE,DESCRIPTION) VALUES (1,3,500,"SAMSUNG PHONE");
INSERT INTO ITEM(PRODUCT_ID,RATING,PRICE,DESCRIPTION) VALUES (1,4,1000,"MICROMAX");

INSERT INTO ITEM(PRODUCT_ID,RATING,PRICE,DESCRIPTION) VALUES (2,4,1000,"DELL");
INSERT INTO ITEM(PRODUCT_ID,RATING,PRICE,DESCRIPTION) VALUES (2,4,1000,"APPLE");
INSERT INTO ITEM(PRODUCT_ID,RATING,PRICE,DESCRIPTION) VALUES (2,4,1000,"LENOVO");
